services:
  question:
    image: golang:1.23-alpine
    container_name: peer-prep-question
    working_dir: /app
    env_file:
      - ./peer-prep-be/.env
    volumes:
      - ./peer-prep-be:/app
    command: sh -c "go run ./src/server.go"
    ports:
      - "8080:8080"
    environment:
      - CGO_ENABLED=0
    depends_on:
      - mongo
    networks:
      - ihatefrontend      

  mongo:
    image: mongo:6.0
    container_name: peer-prep-mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - ihatefrontend    

  nginx:
    image: nginx:alpine
    container_name: peer-prep-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - question
      # - user
      # - collaboration
      # - websocket
    networks:
      - ihatefrontend

networks:
  rabbitmqNetwork:
    driver: bridge
  ihatefrontend:
    driver: bridge  

volumes:
  mongo_data:
  rabbitmq_data: