version: '3.8'

services:
  backend:
    image: golang:1.23-alpine  # Use the Go Alpine image for a minimal environment
    container_name: peer-prep-be
    working_dir: /app
    env_file: 
      - .env
    volumes:
      - .:/app  # Mount the current directory (root) to /app in the container
    command: sh -c "go run ./src/server.go"
    ports:
      - "8080:8080"
    environment:
      - CGO_ENABLED=0  # Ensure no CGO usage, adjust if necessary
    depends_on:
      - mongo  # MongoDB service

  mongo:
    image: mongo:6.0
    container_name: peer-prep-mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
